const canvas=document.getElementById('universe'),ctx=canvas.getContext('2d',{alpha:false});
let W,H,DPR,stars=[],dust=[],meteors=[],bursts=[],intensity=1,last=0,pointer={x:.5,y:.5};
const rand=(a,b)=>a+Math.random()*(b-a), clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);makeSky()}
function makeSky(){stars=Array.from({length:Math.floor(W*H/3100)},()=>({x:Math.random()*W,y:Math.random()*H,z:rand(.3,1.8),a:rand(.2,1),p:rand(0,7),s:rand(.6,2.2)}));dust=Array.from({length:70},()=>({x:rand(0,W),y:rand(0,H),r:rand(20,120),h:Math.random()>.5?270:195,a:rand(.006,.025)}))}
function background(t){let g=ctx.createRadialGradient(W*.69,H*.42,5,W*.69,H*.42,Math.max(W,H)*.8);g.addColorStop(0,'#291543');g.addColorStop(.34,'#0c0821');g.addColorStop(.72,'#050312');g.addColorStop(1,'#010107');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
  ctx.save();ctx.globalCompositeOperation='screen';dust.forEach(n=>{let g=ctx.createRadialGradient(n.x,n.y,0,n.x,n.y,n.r);g.addColorStop(0,`hsla(${n.h},80%,60%,${n.a})`);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.arc(n.x,n.y,n.r,0,Math.PI*2);ctx.fill()});ctx.restore();
  ctx.save();ctx.globalCompositeOperation='screen';stars.forEach(s=>{let tw=.38+.62*Math.pow(Math.sin(t*.001*s.s+s.p),2),x=s.x+(pointer.x-.5)*s.z*-11,y=s.y+(pointer.y-.5)*s.z*-8,r=s.z*tw*intensity;ctx.fillStyle=`rgba(${s.z>1.2?'255,230,165':'210,221,255'},${s.a*tw})`;ctx.beginPath();ctx.arc(x,y,Math.max(.35,r),0,7);ctx.fill();if(r>1.4){ctx.strokeStyle=`rgba(255,226,145,${s.a*tw*.45})`;ctx.beginPath();ctx.moveTo(x-r*4,y);ctx.lineTo(x+r*4,y);ctx.moveTo(x,y-r*4);ctx.lineTo(x,y+r*4);ctx.stroke()}});ctx.restore()}
function spawnMeteor(){meteors.push({x:rand(-100,W*.6),y:rand(-50,H*.28),vx:rand(8,14),vy:rand(3,5),life:1})}
function effects(){ctx.save();ctx.globalCompositeOperation='screen';meteors.forEach((m,i)=>{m.x+=m.vx;m.y+=m.vy;m.life-=.012;let g=ctx.createLinearGradient(m.x,m.y,m.x-m.vx*12,m.y-m.vy*12);g.addColorStop(0,`rgba(255,245,190,${m.life})`);g.addColorStop(1,'transparent');ctx.strokeStyle=g;ctx.lineWidth=2.3;ctx.beginPath();ctx.moveTo(m.x,m.y);ctx.lineTo(m.x-m.vx*14,m.y-m.vy*14);ctx.stroke();if(m.life<=0)meteors.splice(i,1)});bursts.forEach((b,i)=>{b.r+=2.3;b.a-=.018;ctx.strokeStyle=`rgba(255,215,80,${b.a})`;ctx.lineWidth=1;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.stroke();if(b.a<=0)bursts.splice(i,1)});ctx.restore()}
function loop(t){background(t);effects();if(Math.random()<.0022*intensity)spawnMeteor();let rose=document.getElementById('roseWrap');rose.style.setProperty('--float',`${Math.sin(t*.00075)*8}px`);requestAnimationFrame(loop)}
addEventListener('resize',resize);addEventListener('pointermove',e=>{pointer.x=e.clientX/W;pointer.y=e.clientY/H;document.getElementById('roseWrap').style.setProperty('--ry',`${(pointer.x-.5)*7}deg`);document.getElementById('roseWrap').style.setProperty('--rx',`${(.5-pointer.y)*4}deg`)});
canvas.addEventListener('pointerdown',e=>bursts.push({x:e.clientX,y:e.clientY,r:3,a:.85}));
document.getElementById('sparkButton').onclick=()=>{intensity=intensity>=2?0.65:intensity+.45;for(let i=0;i<3;i++)setTimeout(spawnMeteor,i*180)};
document.getElementById('fullButton').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
document.getElementById('wishButton').onclick=e=>{e.currentTarget.classList.add('wished');e.currentTarget.innerHTML='<span>✦</span> Deseo enviado al universo';let r=e.currentTarget.getBoundingClientRect();for(let i=0;i<42;i++){let p=document.createElement('i');p.className='wish-particle';p.textContent=Math.random()>.35?'✦':'•';p.style.left=(r.left+r.width/2)+'px';p.style.top=(r.top+r.height/2)+'px';p.style.setProperty('--x',rand(-220,220)+'px');p.style.setProperty('--y',rand(-260,80)+'px');p.style.setProperty('--d',rand(1.2,2.6)+'s');document.body.appendChild(p);setTimeout(()=>p.remove(),2700)}};
let audioCtx,hum;document.getElementById('soundButton').onclick=function(){if(!audioCtx){audioCtx=new AudioContext();let master=audioCtx.createGain();master.gain.value=.035;master.connect(audioCtx.destination);[110,164.81,220].forEach((f,i)=>{let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=f;g.gain.value=[.45,.22,.13][i];o.connect(g).connect(master);o.start()});hum=true;this.textContent='♫'}else{audioCtx.resume();hum=!hum;audioCtx.destination.channelCount;this.textContent=hum?'♫':'♪'}};
resize();requestAnimationFrame(loop);addEventListener('load',()=>setTimeout(()=>document.getElementById('loading').classList.add('hidden'),650));
